---
# Nagios NRPE Server role by Mooash

# Include variables at the start so they're in scope
- name: Include OS-Specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Include RedHat specific variables due to x64/x86 differences
- name: Include RedHat x86 variables
  include_vars: "{{ ansible_os_family }}-x86.yml"
  when: "'{{ansible_os_family}}' == 'RedHat' and '{{ansible_architecture}}' == 'i386'"

- name: Include RedHat x64 variables
  include_vars: "{{ ansible_os_family }}-x64.yml"
  when: "'{{ansible_os_family}}' == 'RedHat' and '{{ansible_architecture}}' == 'x86_64'"

# Install our needed packages for each specific OS
# Debian packages
- include: packages-debian.yml
  when: "ansible_os_family == 'Debian'"

# RedHat based packages
- include: packages-redhat.yml
  when: "ansible_os_family == 'RedHat'"

# Arch Linux based packages
- include: packages-archlinux.yml
  when: "ansible_os_family == 'Archlinux'"

# Solaris based packages
- include: packages-Solaris.yml
  when: "ansible_os_family == 'Solaris'"
  
# Create our config
- name: Create nrpe.cfg from template
  template: >
    src="nrpe.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-server

# Create nrpe_ansible.cfg
- name: Create nrpe_ansible.cfg from template
  template: >
    src="nrpe_ansible.cfg.j2"
    dest="{{ nagios_nrpe_server_dir }}/nrpe_ansible.cfg"
    owner=root group=root mode=0644
  notify: restart nagios-nrpe-server

# Sync our plugins
- name: Install global plugins
  copy: >
    src="{{ item }}"
    dest="{{ nagios_nrpe_server_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
    - plugins/global/*

# Install per-server plugins
- name: Install per-server plugins
  copy: >
    src="{{ item }}"
    dest="{{ nagios_nrpe_server_plugins_dir }}/"
    owner=root group=root mode=0755
  with_fileglob:
    - "plugins/{{ ansible_fqdn }}/*"

# Ensure NRPE server is running and will start at boot
- name: Ensure NRPE server is running
  service: name="{{ nagios_nrpe_server_service }}" state=started enabled=yes
